export interface UserPost {
  id: number;
  username: string;
  post: string;
  createdAt: Date;
  like: boolean;
}

export const userPosts: UserPost[] = [
  {
    id: 1,
    username: 'CoolCat23',
    post: 'Just finished reading an amazing book. Highly recommend!',
    createdAt: new Date('2023-12-25T08:00:00Z'),
    like: false,
  },
  {
    id: 2,
    username: 'GamerGirl99',
    post: 'New high score in my favorite game! 🎮 #GamingLife',
    createdAt: new Date('2023-12-24T15:30:00Z'),
    like: false,
  },
  {
    id: 3,
    username: 'FoodieExplorer',
    post: 'Tried a new restaurant today. The food was delicious! 🍔🍟',
    createdAt: new Date('2023-12-23T18:45:00Z'),
    like: false,
  },
  {
    id: 4,
    username: 'TechGeek101',
    post: "Excited about the latest tech release. Can't wait to get my hands on it!",
    createdAt: new Date('2023-12-22T12:10:00Z'),
    like: false,
  },
  {
    id: 5,
    username: 'TravelBug22',
    post: 'Just booked a spontaneous trip to [destination]. Adventure awaits! ✈️🌍',
    createdAt: new Date('2023-12-21T09:20:00Z'),
    like: false,
  },
  {
    id: 6,
    username: 'FitnessFreak',
    post: 'Hit a new personal record at the gym today. Hard work pays off! 💪',
    createdAt: new Date('2023-12-20T16:05:00Z'),
    like: false,
  },
  {
    id: 7,
    username: 'ArtisticSoul',
    post: 'Finished my latest art project. What do you think of it?',
    createdAt: new Date('2023-12-19T20:30:00Z'),
    like: false,
  },
  {
    id: 8,
    username: 'BookWorm123',
    post: 'Lost in the world of books again. Any recommendations for my next read?',
    createdAt: new Date('2023-12-18T11:45:00Z'),
    like: false,
  },
  {
    id: 9,
    username: 'DIYMastermind',
    post: 'Just completed a DIY project. Feeling accomplished! 🔨',
    createdAt: new Date('2023-12-17T14:55:00Z'),
    like: false,
  },
  {
    id: 10,
    username: 'Fashionista',
    post: 'OOTD: Loving my outfit today. #FashionGoals',
    createdAt: new Date('2023-12-16T19:10:00Z'),
    like: false,
  },
  {
    id: 11,
    username: 'MemeLord',
    post: 'Dropping the latest meme. Who can relate? 😂',
    createdAt: new Date('2023-12-15T22:40:00Z'),
    like: false,
  },
  {
    id: 12,
    username: 'NatureLover',
    post: 'Spent the day hiking and reconnecting with nature. 🌲🌳',
    createdAt: new Date('2023-12-14T17:15:00Z'),
    like: false,
  },
  {
    id: 13,
    username: 'MusicJunkie',
    post: 'Discovered an amazing new artist. Check out their latest song!',
    createdAt: new Date('2023-12-13T13:25:00Z'),
    like: false,
  },
  {
    id: 14,
    username: 'PositiveVibesOnly',
    post: 'Sending good vibes to everyone today. Stay positive! ✨',
    createdAt: new Date('2023-12-12T09:50:00Z'),
    like: false,
  },
  {
    id: 15,
    username: 'DIYChef',
    post: 'Experimenting in the kitchen. Just created a delicious new recipe.',
    createdAt: new Date('2023-12-11T14:30:00Z'),
    like: false,
  },
  {
    id: 16,
    username: 'FitnessFanatic',
    post: 'Early morning workout complete. Ready to conquer the day!',
    createdAt: new Date('2023-12-10T18:20:00Z'),
    like: false,
  },
  {
    id: 17,
    username: 'PetLover',
    post: 'My furry friend always knows how to brighten my day. 🐾❤️',
    createdAt: new Date('2023-12-09T11:15:00Z'),
    like: false,
  },
  {
    id: 18,
    username: 'FilmBuff',
    post: "Movie night recommendation: [Movie Title]. It's a must-watch!",
    createdAt: new Date('2023-12-08T20:05:00Z'),
    like: false,
  },
  {
    id: 19,
    username: 'CodeWizard',
    post: 'Solved a complex coding problem today. Feeling accomplished!',
    createdAt: new Date('2023-12-07T16:45:00Z'),
    like: false,
  },
  {
    id: 20,
    username: 'StarGazer',
    post: 'Spent the evening stargazing. The universe is so fascinating. ✨🌌',
    createdAt: new Date('2023-12-06T12:30:00Z'),
    like: false,
  },
  {
    id: 21,
    username: 'FashionForward',
    post: 'Just got my hands on the latest fashion trends. Loving my new wardrobe!',
    createdAt: new Date('2023-12-05T15:55:00Z'),
    like: false,
  },
  {
    id: 22,
    username: 'CoffeeLover',
    post: 'Nothing beats a cozy morning with a cup of coffee. ☕️',
    createdAt: new Date('2023-12-04T09:40:00Z'),
    like: false,
  },
  {
    id: 23,
    username: 'TechEnthusiast',
    post: "Geeking out over the latest gadgets. Can't wait to try them out!",
    createdAt: new Date('2023-12-03T19:20:00Z'),
    like: false,
  },
  {
    id: 24,
    username: 'TravelDiaries',
    post: 'Documenting my travel adventures. Where to next? 🗺️',
    createdAt: new Date('2023-12-02T14:10:00Z'),
    like: false,
  },
  {
    id: 25,
    username: 'MotivationMonday',
    post: "Starting the week with positive vibes and motivation. Let's crush our goals! 💪",
    createdAt: new Date('2023-12-01T17:30:00Z'),
    like: false,
  },
];
